# Generated by Django 4.1.2 on 2022-10-24 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=100)),
                ("to_name", models.CharField(blank=True, max_length=100, null=True)),
                ("flag", models.CharField(blank=True, max_length=10, null=True)),
                ("visa_id", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "covid_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user_feedback",
                    models.IntegerField(choices=[(1, "yes"), (2, "no")], null=True),
                ),
                (
                    "user_feedback_timestamp",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("closed", models.BooleanField(default=False)),
            ],
        ),
    ]
