# Generated by Django 4.1.2 on 2022-10-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
